version: '3.8'

services:
  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    depends_on:
      - backend

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iotplatform
      - SPRING_DATASOURCE_USERNAME=iotuser
      - SPRING_DATASOURCE_PASSWORD=iotpassword
      - INFLUX_URL=http://influxdb:8086
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - influxdb
      - redis

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=iotplatform
      - POSTGRES_USER=iotuser
      - POSTGRES_PASSWORD=iotpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # InfluxDB for time-series data
  influxdb:
    image: influxdb:2.7-alpine
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=telemetry
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  influxdb_data:
  redis_data: