spring:
  application:
    name: iot-platform-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/iotplatform
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: never
      continue-on-error: true
      schema-locations: classpath:schema.sql

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 31536000000

# Logging
logging:
  level:
    com.iotplatform: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
